#!/usr/bin/env ruby
$:.unshift(File.join(File.dirname(__FILE__), 'lib'))

# deps
require 'irb'
require 'elasticsearch'

require 'query'
require 'writer'

def populate
  Writer.new.upsert
end

def search(terms)
  Query.new(terms).find_all
  nil
end

def find(id)
  Query.new(id, 1).find
  nil
end

IRB.start(__FILE__)
