#!/usr/bin/env ruby
$:.unshift(File.join(File.dirname(__FILE__), 'lib'))

require 'irb'
require 'elasticsearch'

require 'config'
require 'book_parser'
require 'book_downloader'

def index
  return 'index already exists' if index_exists?
  CLIENT.indices.create(index: INDEX_NAME, **MAPPING)
end
def delete
  CLIENT.indices.delete(index: INDEX_NAME) if index_exists?
end
def index_exists?
  CLIENT.indices.exists?(index: INDEX_NAME)
end
def war_and_peace
  raw_book = BookDownloader.new.get_book
  parser   = BookParser.new(raw_book)
  parser.call
  puts parser.books
end
IRB.start(__FILE__)
